server:
  port: 3344

spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          uri: git@github.com:426Brian/microservicecloud-config.git
          search-paths:
            - microservicecloud-config
      label: master
  rabbitmq:
    host: 192.168.1.101
    port: 5672
    username: guest
    password: guest


eureka:
  instance:
    instance-id: cloud-config-center3344
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'