server:
  port: 8080

spring:
  application:
    name: cloud-payment-consumer

eureka:
  instance:
    instance-id: feign-hystrix-consumer8080
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.springcloud.service.PaymentFeignService: debug

feign:
  hystrix:
    enabled: true