server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**
        - id: payment_route2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            #- After=2020-09-13T15:33:53.417+08:00[Asia/Shanghai]
            #- Cookie=username,Brian

eureka:
  instance:
    instance-id: cloud-gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

