server:
  port: 8083

spring:
  application:
    name: nacos-order8083
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-provider